# Generated by Django 4.0.6 on 2022-08-16 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Il',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='YerlesimTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=50, verbose_name='Yerleşim türü')),
            ],
        ),
        migrations.CreateModel(
            name='TarihiYer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=300, verbose_name='Tarihin yerin adı')),
                ('aciklama', models.TextField(max_length=5000, verbose_name='Detaylar')),
                ('enlem', models.FloatField(verbose_name='Enlem')),
                ('boylam', models.FloatField(verbose_name='Boylam')),
                ('ilce', models.CharField(max_length=50, verbose_name='İlçe')),
                ('ekleyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen kullanıcı')),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envanter.il')),
                ('yerlesim_turu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envanter.yerlesimturu')),
            ],
        ),
        migrations.CreateModel(
            name='Resim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='')),
                ('tarihi_yer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envanter.tarihiyer')),
            ],
        ),
    ]
